feature: добавлен функцонал удаления пользователей и фильмов - добавл…
sergey-oreshkin/java-filmorate pull request #16
Opened 2022-06-29 07:47 UTC by grigory-pc

…ены методы в соответствующие контроллеры, сервисы и классы. В 'schema.sql' в CONSTRAINT-ы добавлено правило удаления ON DELETE CASCADE для соответствующих ключей, чтобы новый функционал удаления работал корректно

2022-06-29 09:26 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean delete(@Valid @PathVariable long id) {
Все методы удаления возвращают boolean, но нигде эти возвращаемые значения не проверяются и не используются. Может лучше изменить на void?

2022-06-29 09:29 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Лучше убрать эту пустую строку

2022-06-29 09:30 UTC, rs-popov commented on src/main/resources/schema.sql
> +    id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
Тут лишний пробел перед запятой

2022-06-29 09:32 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmstorage/FilmDbStorage.java
> +
Мне кажется, что здесь можно не оставлять пустую строку. метод и так всего из двух строк

2022-06-29 09:33 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/UserDbStorage.java
> +
тоже что и для FilmDbStorage

2022-06-30 02:00 UTC, sergey-oreshkin requested changes
**нужно доработать**
мне не нравится возвращать boolean из контроллера
у нас все таки REST так что метод delete должен отвечать либо код 200 при удалении либо код 404 если такой фильм не найден.
а тело ответа либо пустое, либо давай он будет возвращать этот фильм обратно, чтоб на той стороне с ним могли попрощаться )

2022-06-30 02:08 UTC, sergey-oreshkin commented
и обрати внимание что Роман написал, может быть некоторые замечания тоже стоит исправить

2022-06-30 09:46 UTC, grigory-pc commented on src/main/java/ru/yandex/practicum/filmorate/storage/filmstorage/FilmDbStorage.java
> +
По правилам оформления, на сколько я помню, return должен отделяться пропуском (пустой строкой). Но если он после строки с одним символом "}", то тут доп строку не нужно отступать.

2022-06-30 09:47 UTC, grigory-pc commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Поправил

2022-06-30 11:46 UTC, grigory-pc commented
> **нужно доработать** мне не нравится возвращать boolean из контроллера у нас все таки REST так что метод delete должен отвечать либо код 200 при удалении либо код 404 если такой фильм не найден. а тело ответа либо пустое, либо давай он будет возвращать этот фильм обратно, чтоб на той стороне с ним могли попрощаться )



> **нужно доработать** мне не нравится возвращать boolean из контроллера у нас все таки REST так что метод delete должен отвечать либо код 200 при удалении либо код 404 если такой фильм не найден. а тело ответа либо пустое, либо давай он будет возвращать этот фильм обратно, чтоб на той стороне с ним могли попрощаться )

Сделал Void для котнроллера, так как не вижу смысла возвращать объект, который уже удалён. Но для сервиса и DAO оставил булево значение, так как это полезно будет для тестов.

2022-06-30 11:54 UTC, sergey-oreshkin approved these changes
все ок

2022-07-02 13:26 UTC, grigory-pc commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public boolean delete(@Valid @PathVariable long id) {
В контроллере поменял на void

2022-07-02 13:27 UTC, grigory-pc commented on src/main/java/ru/yandex/practicum/filmorate/storage/userstorage/UserDbStorage.java
> +
для DAO, и сервиса оставил булево значение, так как это удобно для тестов

2022-07-03 09:08 UTC, aitski approved these changes

2022-07-03 09:20 UTC, merged