function: "Отзывы". Добавление, редактирование, удаление, получение по айди, получение списка отзывов по айди фильма, лайк/дизлайк отзыва с счетчиком
sergey-oreshkin/java-filmorate pull request #18
Opened 2022-06-29 10:31 UTC by aitski

2022-06-30 02:38 UTC, sergey-oreshkin requested changes
хорошая работа!
только напиши пожалуйста джавадоки над всеми новыми классами кторые ты написал
на методы можешь не писать
и исправь пару замечаний

2022-06-30 02:38 UTC, sergey-oreshkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
допиши пожалуйста джавадок над классом хотябы, на методы можно не писать если сделал целый класс

2022-06-30 02:38 UTC, sergey-oreshkin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateFilmId(review.getUserId());
здесь нужно вызвать validateUserId наверно

2022-06-30 02:38 UTC, sergey-oreshkin commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateFilmId(review.getUserId());
здесь тоже наверно нужно вызвать validateUserId

2022-06-30 03:41 UTC, aitski commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
готово

2022-06-30 03:41 UTC, aitski commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateFilmId(review.getUserId());
готово

2022-06-30 03:41 UTC, aitski commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        validateFilmId(review.getUserId());
готово

2022-06-30 03:56 UTC, sergey-oreshkin approved these changes
все ок

2022-07-01 07:04 UTC, rs-popov approved these changes
Все отлично!

2022-07-01 07:36 UTC, merged