feat: добавлена функциональность «Лента событий»
sergey-oreshkin/java-filmorate pull request #23
Opened 2022-07-02 12:08 UTC by rs-popov

2022-07-02 13:21 UTC, sergey-oreshkin requested changes
то что код работает и проходит тесты очень хорошо, но не достаточно
твой подход к внедрению отслеживания событий нарушает open-closed principle, второй из принципов SOLID и это уже как минимум вызвало проблему с мержем, а в большом проекте вызовет проблему и с поддерживаемостью
одним из хороших решений тут было бы проскировать вызовы для их отслеживания
мы уже делали это в проекте по трекеру задач когда добавляли функциональность сохранения в файл
нужно написать новые классы сервисов которые бы наследовались от текущих реализаций, там через super вызывать метод родительского класса и после этого вызова сохранять событие. и потом просто подменить реализацию которая внедряется как зависимость в контроллер
второе хорошее решение это использовать [spring AOP](https://docs.spring.io/spring-framework/docs/2.5.x/reference/aop.html) который делает то же самое, но в декларативном стиле. то есть там прописываешь при вызове каких методов какой функционал должен дополнительно вызываться.
я сам им еще не пользовался, и пока из теории не понял как там гарантировать транзакционность, но можешь попробовать реализовать так, если тебе интересно, или хотя бы на самописных прокси классах. такую реализацию не очень хочется показывать ревьюеру

2022-07-02 13:21 UTC, sergey-oreshkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                    .filter(film -> film.getGenres() != null)
постарайся в будущем не редактировать строки которые писал не ты без веской на то причины
тем более на эти строки есть пулл реквест и ты мог бы отметить там что в этих местах требуется редакция
таким образом наш репозиторий избежал бы мерж конфликтов

2022-07-02 13:33 UTC, sergey-oreshkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    long timestamp = System.currentTimeMillis();
не нужно инициализировать поля в модели, это может вызвать ошибки в маппере
хотя @Builder.Default это хорошо ты написал
записывать время можно на стороне БД, там можно написать что то типа default current timestamp

2022-07-02 13:44 UTC, sergey-oreshkin commented on src/main/resources/schema.sql
> +    event_time  BIGINT,
тут стоит написать event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP

2022-07-03 12:55 UTC, sergey-oreshkin approved these changes
с аоп еще сам не разобрался, но тесты ок, и код вроде неплохой, так что апрув

2022-07-03 13:32 UTC, grigory-pc approved these changes
Всё супер!

2022-07-03 13:35 UTC, merged