Enum gt
sergey-oreshkin/java-filmorate pull request #26
Opened 2022-07-05 08:49 UTC by grigory-pc

2022-07-05 15:41 UTC, sergey-oreshkin approved these changes
код посмотрел, меня устраивает. не запускал не проверял

2022-07-06 03:41 UTC, rs-popov requested changes
Все отлично, но с названием переменной operationType не проходят тесты из ветки add-feed.  Нужно вернуть прежнее - с ним все тесты проходят

2022-07-06 03:41 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    OperationType operationType;
С названием переменной operationType не проходят тесты из ветки add-feed. Лучше вернуть прежнее название operation

2022-07-06 14:48 UTC, sergey-oreshkin approved these changes

2022-07-07 02:34 UTC, rs-popov approved these changes

2022-07-07 04:10 UTC, merged